# Build block:
# Build the app and keep dist/ as artifact
build:
  image: node
  stage: build
  script:
    - yarn
    - yarn run build
  artifacts:
    paths:
      - build/

# Test block:
# Test the app
test:
  image: node
  stage: test
  script:
    - yarn
    - yarn run test:coverage

# Deploy Staging block:
# Upload the dist/ artifact to Google Cloud when pushing on develop
deploy:
  image: davidkassa/yarn-angular-cli-firebase-tools
  stage: deploy
  script:
    - firebase use --token $FIREBASE_DEPLOY_KEY
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_JOB_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
